import cv2

img = cv2.imread("1.png")
blur = cv2.GaussianBlur(img, (3, 3), 0)
cv2.imshow("g3", blur)
blur = cv2.GaussianBlur(img, (5, 5), 0)
cv2.imshow("g5", blur)
blur = cv2.GaussianBlur(img, (7, 7), 0)
cv2.imshow("g7", blur)
blur = cv2.blur(img, (3, 3))
cv2.imshow("b3", blur)
blur = cv2.blur(img, (5, 5))
cv2.imshow("b5", blur)
blur = cv2.blur(img, (7, 7))
cv2.imshow("b7", blur)
blur = cv2.medianBlur(img, 3)
cv2.imshow("m3", blur)
blur = cv2.medianBlur(img, 5)
cv2.imshow("m5", blur)
blur = cv2.medianBlur(img, 7)
cv2.imshow("m7", blur)
cv2.waitKey(0)
